### ISSUE TITLE
Dependency conflict in stone & six

### ISSUE THREAD

**Issue by Miesvanderlippe** [koenbuyens/securityheaders#11]
The version of 'stone' in my installation requires a version of 'six' that's equal to or greater than 1.12.0. Your requirements.txt has the 5 year old 1.11.0. Please consider bumping the version or creating laxer version requirements like a minimum version or a fixed major version.

**Comment by koenbuyens** [comment]
Please make a pull request and I will accept it.

**Comment by Miesvanderlippe** [comment]
Note to self: also include 'burp' in requirements.txt
