### ISSUE TITLE
Parse headers separated by comma

### ISSUE THREAD

**Issue by upils** [koenbuyens/securityheaders#3]
As stated in the [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2), header values should be separated by comma and not semicolon.

Even if the majority of values appears to be separated by semicolon, it's not always the case thus these values are considered unknown.

**Comment by upils** [comment]
Fix in https://github.com/koenbuyens/securityheaders/pull/4

**Comment by koenbuyens** [comment]
accepted.

**Comment by upils** [comment]
Would you be interested in setting up automatic tests via CI ?
